-keep class com.yausername.youtubedl_android.** { *; }
-keep class com.yausername.ffmpeg.** { *; }
-keep class org.apache.commons.compress.archivers.zip.** { *; }
-keep interface org.apache.commons.compress.archivers.zip.** { *; }
-keep class com.redcoal.redmedia.mobile.data.** { *; }
